function htmlContent = createErrorHTML(errorMessage)
    % Creates standardized HTML error messages
    htmlContent = ['<html><head><style>', ...
                 'div.error {color: red; text-align: center; margin-top: 10px; font-weight: bold; ', ...
                 'padding: 10px; border: 1px solid red; border-radius: 5px;}', ...
                 '</style></head><body>', ...
                 '<div class="error">', errorMessage, '</div>', ...
                 '</body></html>'];
end