function html = createErrorHTML(message)
    html = ['<html><head><style>', ...
            'body { font-family: Arial, sans-serif; margin: 0; padding: 0; }', ...
            '.error-box { color: #E74C3C; text-align: center; margin: 20px auto; font-weight: bold; ', ...
            'padding: 15px; border: 1px solid #E74C3C; border-radius: 5px; max-width: 600px; background-color: #FDEDEC; }', ...
            '</style></head><body>', ...
            '<div class="error-box">', message, '</div>', ...
            '</body></html>'];
end