% HTML-Inhalt für Ergebnisanzeige erstellen (angepasst an den Stil der App)
function htmlStr = createHtmlContent(varargin)
    % HTML-Kopf mit Styling
    htmlStr = ['<html><head><style>', ...
        'body {font-family: Arial, sans-serif; font-size: 12px; margin: 0; padding: 10px; color: #333;}', ...
        'h3 {color: #446699; margin-top: 0; margin-bottom: 10px;}', ...
        '.info-section {margin-bottom: 15px; padding: 5px;}', ...
        '.result-value {font-weight: bold; color: #000;}', ...
        '.warning {color: #cc3333; font-weight: bold;}', ...
        '.success {color: #33aa33; font-weight: bold;}', ...
        '.note {color: #666; font-style: italic; font-size: 11px;}', ...
        'table {width: 100%; border-collapse: collapse;}', ...
        'th {background-color: #446699; color: white; text-align: left; padding: 5px;}', ...
        'td {padding: 4px; border: 1px solid #ddd;}', ...
        'tr:nth-child(even) {background-color: #f9f9f9;}', ...
        '</style></head><body>'];
    
    % Ersten Parameter als Überschrift hinzufügen
    if nargin > 0
        htmlStr = [htmlStr, '<h3>', varargin{1}, '</h3><div class="info-section">'];
    end
    
    % Weitere Parameter als Textzeilen hinzufügen
    for i = 2:nargin
        % Prüfen, ob es sich um eine leere Zeile handelt
        if isempty(varargin{i})
            htmlStr = [htmlStr, '<br>'];
        else
            htmlStr = [htmlStr, '<div>', varargin{i}, '</div>'];
        end
    end
    
    % HTML abschließen
    htmlStr = [htmlStr, '</div></body></html>'];
end