% Function to create an enhanced HTML table for results
function htmlContent = createResultsTable(metric, successCount, numSimulations, statisticsData, correlationData)
    % Create HTML for a well-styled results table
    
    % HTML Header with styling - matching other tables in the app
    htmlHeader = [...
        '<html><head><style>', ...
        'body {font-family: Arial, sans-serif; font-size: 12px; margin: 0; padding: 10px; color: #333;}', ...
        'h3 {color: #446699; margin-top: 0; margin-bottom: 10px;}', ...
        'table { border-collapse: collapse; width: 100%; font-family: Arial, sans-serif; margin-bottom: 15px; }', ...
        'th { background-color: #4472C4; color: white; padding: 8px; text-align: center; font-size: 14px; }', ...
        'td { border: 1px solid #DDDDDD; padding: 8px; font-size: 13px; }', ...
        'td:first-child { font-weight: bold; }', ...
        'tr:nth-child(even) { background-color: #F2F2F2; }', ...
        'tr:hover { background-color: #E8F4F8; }', ...
        '.section-header { background-color: #5D87B1; color: white; font-weight: bold; }', ...
        '.success-rate { color: #2ECC71; font-weight: bold; }', ...
        '.failure-rate { color: #E74C3C; font-weight: bold; }', ...
        '.correlation-positive { color: #27AE60; }', ...
        '.correlation-negative { color: #C0392B; }', ...
        '.metric-header { background-color: #4472C4; color: white; font-weight: bold; }', ...
        '</style></head><body>'];
    
    % Main heading
    htmlBody = ['<h3>Monte Carlo Simulation Results: ' metric '</h3>'];
    
    % Simulation info with success rate
    successRate = 100 * successCount / numSimulations;
    htmlBody = [htmlBody, ...
        '<table>', ...
        '<tr><th colspan="2">Simulation Information</th></tr>', ...
        '<tr><td width="50%">Total Simulations</td><td>' num2str(numSimulations) '</td></tr>', ...
        '<tr><td>Successful Simulations</td><td>' num2str(successCount) ...
        ' <span class="success-rate">(' num2str(successRate, '%.1f') '%)</span></td></tr>'];
    
    if successCount < numSimulations
        failureRate = 100 * (numSimulations - successCount) / numSimulations;
        htmlBody = [htmlBody, ...
            '<tr><td>Failed Simulations</td><td>' num2str(numSimulations - successCount) ...
            ' <span class="failure-rate">(' num2str(failureRate, '%.1f') '%)</span></td></tr>'];
    end
    
    htmlBody = [htmlBody, '</table>'];
    
    % Statistics table
    htmlBody = [htmlBody, ...
        '<table>', ...
        '<tr><th colspan="3">' metric ' Statistics</th></tr>'];
    
    % Add each statistic row
    for i = 1:length(statisticsData)
        stat = statisticsData{i};
        htmlBody = [htmlBody, ...
            '<tr><td width="30%">' stat{1} '</td><td>' stat{2} '</td><td>' stat{3} '</td></tr>'];
    end
    
    htmlBody = [htmlBody, '</table>'];
    
    % Correlation table
    htmlBody = [htmlBody, ...
        '<table>', ...
        '<tr><th colspan="3">Parameter Correlations with ' metric '</th></tr>', ...
        '<tr><th width="30%">Parameter</th><th>Correlation</th><th>Interpretation</th></tr>'];
    
    % Add each correlation row
    for i = 1:length(correlationData)
        corr = correlationData{i};
        
        % Determine color class based on correlation value
        corrValue = str2double(strrep(corr{2}, 'N/A', 'NaN'));
        if isnan(corrValue)
            colorClass = '';
        elseif corrValue > 0
            colorClass = 'correlation-positive';
        else
            colorClass = 'correlation-negative';
        end
        
        htmlBody = [htmlBody, ...
            '<tr><td>' corr{1} '</td><td class="' colorClass '">' corr{2} ...
            '</td><td>' corr{3} '</td></tr>'];
    end
    
    htmlBody = [htmlBody, '</table>'];
    
    % Interpretation notes
    htmlBody = [htmlBody, ...
        '<table>', ...
        '<tr><th>Interpretation Notes</th></tr>', ...
        '<tr><td>', ...
        'Correlation values range from -1 to 1:<br>', ...
        '• Positive values indicate parameters increase with the metric<br>', ...
        '• Negative values indicate parameters decrease with the metric<br>', ...
        '• Larger absolute values indicate stronger relationships<br>', ...
        'Coefficient of Variation (CoV) measures relative variability', ...
        '</td></tr>', ...
        '</table>'];
    
    % Complete HTML
    htmlContent = [htmlHeader, htmlBody, '</body></html>'];
end