% Function to create a comprehensive HTML table for all metrics
function htmlContent = createComprehensiveResultsTable(successCount, numSimulations, metricsData, correlationData)
    % Create HTML for a well-styled comprehensive results table showing all metrics
    
    % HTML Header with styling - matching other tables in the app
    htmlHeader = [...
        '<html><head><style>', ...
        'body {font-family: Arial, sans-serif; font-size: 12px; margin: 0; padding: 10px; color: #333;}', ...
        'h3 {color: #446699; margin-top: 0; margin-bottom: 10px;}', ...
        'table { border-collapse: collapse; width: 100%; font-family: Arial, sans-serif; margin-bottom: 15px; }', ...
        'th { background-color: #4472C4; color: white; padding: 8px; text-align: center; font-size: 14px; }', ...
        'td { border: 1px solid #DDDDDD; padding: 8px; font-size: 13px; }', ...
        'td:first-child { font-weight: bold; }', ...
        'tr:nth-child(even) { background-color: #F2F2F2; }', ...
        'tr:hover { background-color: #E8F4F8; }', ...
        '.section-header { background-color: #5D87B1; color: white; font-weight: bold; }', ...
        '.success-rate { color: #2ECC71; font-weight: bold; }', ...
        '.failure-rate { color: #E74C3C; font-weight: bold; }', ...
        '.correlation-positive { color: #27AE60; }', ...
        '.correlation-negative { color: #C0392B; }', ...
        '.metric-header { background-color: #4472C4; color: white; font-weight: bold; }', ...
        '</style></head><body>'];
        
    % Main heading
    htmlBody = '<h3>Monte Carlo Simulation Results: All Metrics</h3>';
    
    % Simulation info with success rate
    successRate = 100 * successCount / numSimulations;
    htmlBody = [htmlBody, ...
        '<table>', ...
        '<tr><th colspan="2">Simulation Information</th></tr>', ...
        '<tr><td width="50%">Total Simulations</td><td>' num2str(numSimulations) '</td></tr>', ...
        '<tr><td>Successful Simulations</td><td>' num2str(successCount) ...
        ' <span class="success-rate">(' num2str(successRate, '%.1f') '%)</span></td></tr>'];
    
    if successCount < numSimulations
        failureRate = 100 * (numSimulations - successCount) / numSimulations;
        htmlBody = [htmlBody, ...
            '<tr><td>Failed Simulations</td><td>' num2str(numSimulations - successCount) ...
            ' <span class="failure-rate">(' num2str(failureRate, '%.1f') '%)</span></td></tr>'];
    end
    
    htmlBody = [htmlBody, '</table>'];
    
    % Statistics for all metrics table
    htmlBody = [htmlBody, ...
        '<table>', ...
        '<tr><th>Metric</th><th>Mean</th><th>Std Dev</th><th>Unit</th><th>Min</th><th>Max</th></tr>'];
    
    % Add each metric row
    for i = 1:length(metricsData)
        metric = metricsData{i};
        htmlBody = [htmlBody, ...
            '<tr><td>' metric{1} '</td><td>' metric{2} '</td><td>' metric{3} ...
            '</td><td>' metric{4} '</td><td>' metric{5} '</td><td>' metric{6} '</td></tr>'];
    end
    
    htmlBody = [htmlBody, '</table>'];
    
    % Correlation matrix table
    htmlBody = [htmlBody, ...
        '<table>', ...
        '<tr><th>Metric</th><th>Kp Correlation</th><th>Ki Correlation</th><th>Kd Correlation</th></tr>'];
    
    % Add each correlation row
    for i = 1:length(correlationData)
        corr = correlationData{i};
        
        % Determine color classes for each correlation value
        corrClass1 = getCorrColorClass(corr{2});
        corrClass2 = getCorrColorClass(corr{3});
        corrClass3 = getCorrColorClass(corr{4});
        
        htmlBody = [htmlBody, ...
            '<tr><td>' corr{1} '</td>', ...
            '<td class="' corrClass1 '">' corr{2} '</td>', ...
            '<td class="' corrClass2 '">' corr{3} '</td>', ...
            '<td class="' corrClass3 '">' corr{4} '</td></tr>'];
    end
    
    htmlBody = [htmlBody, '</table>'];
    
    % Interpretation notes
    htmlBody = [htmlBody, ...
        '<table>', ...
        '<tr><th>Interpretation Notes</th></tr>', ...
        '<tr><td>', ...
        'Correlation interpretation:<br>', ...
        '• <span class="correlation-positive">Positive values</span>: Parameter increases → metric increases<br>', ...
        '• <span class="correlation-negative">Negative values</span>: Parameter increases → metric decreases<br>', ...
        '• Values close to ±1 indicate stronger relationships<br>', ...
        '• Values close to 0 indicate weak or no relationship', ...
        '</td></tr>', ...
        '</table>'];
    
    % Complete HTML
    htmlContent = [htmlHeader, htmlBody, '</body></html>'];
    
    % Helper function to get correlation CSS class
    function cssClass = getCorrColorClass(corrValue)
        % Try to convert to number
        numValue = str2double(strrep(corrValue, 'N/A', 'NaN'));
        if isnan(numValue)
            cssClass = '';
        elseif numValue > 0
            cssClass = 'correlation-positive';
        else
            cssClass = 'correlation-negative';
        end
    end
end