function htmlContent = createCorrelationMatrix(successCount, numSimulations, metricsData)
    % CREATECORRELATIONMATRIX - Create HTML table for correlation analysis results
    % 
    % This function creates an HTML table that presents correlation analysis
    % results between controller parameters and performance metrics
    %
    % Parameters:
    %   successCount - Number of successful simulations
    %   numSimulations - Total number of simulations
    %   metricsData - Cell array of metric data with format:
    %                 {MetricName, Mean, StdDev, CoV, Unit}
    %
    % Returns:
    %   htmlContent - HTML string for the results visualization
    
    % HTML Header with styling - matching other tables in the app
    htmlHeader = [...
        '<html><head><style>', ...
        'body {font-family: Arial, sans-serif; font-size: 12px; margin: 0; padding: 10px; color: #333;}', ...
        'h3 {color: #446699; margin-top: 0; margin-bottom: 10px;}', ...
        'table { border-collapse: collapse; width: 100%; font-family: Arial, sans-serif; margin-bottom: 15px; }', ...
        'th { background-color: #4472C4; color: white; padding: 8px; text-align: center; font-size: 14px; }', ...
        'td { border: 1px solid #DDDDDD; padding: 8px; font-size: 13px; }', ...
        'td:first-child { font-weight: bold; }', ...
        'tr:nth-child(even) { background-color: #F2F2F2; }', ...
        'tr:hover { background-color: #E8F4F8; }', ...
        '.success-rate { color: #2ECC71; font-weight: bold; }', ...
        '.failure-rate { color: #E74C3C; font-weight: bold; }', ...
        '.high-variability { color: #E74C3C; }', ...
        '.low-variability { color: #2ECC71; }', ...
        '.correlation-positive { color: #27AE60; font-weight: bold; }', ...
        '.correlation-negative { color: #C0392B; font-weight: bold; }', ...
        '</style></head><body>'];
        
    % Main heading
    htmlBody = '<h3>Monte Carlo Correlation Analysis</h3>';
    
    % Simulation info with success rate
    successRate = 100 * successCount / numSimulations;
    htmlBody = [htmlBody, ...
        '<table>', ...
        '<tr><th colspan="5">Simulation Summary</th></tr>', ...
        '<tr><td width="20%">Total Simulations</td><td colspan="4">' num2str(numSimulations) '</td></tr>', ...
        '<tr><td>Successful Simulations</td><td colspan="4">' num2str(successCount) ...
        ' <span class="success-rate">(' num2str(successRate, '%.1f') '%)</span></td></tr>'];
    
    if successCount < numSimulations
        failureRate = 100 * (numSimulations - successCount) / numSimulations;
        htmlBody = [htmlBody, ...
            '<tr><td>Failed Simulations</td><td colspan="4">' num2str(numSimulations - successCount) ...
            ' <span class="failure-rate">(' num2str(failureRate, '%.1f') '%)</span></td></tr>'];
    end
    
    htmlBody = [htmlBody, '</table>'];
    
    % Metric summary table
    htmlBody = [htmlBody, ...
        '<table>', ...
        '<tr><th>Metric</th><th>Mean</th><th>Std Dev</th><th>Variability</th><th>Unit</th></tr>'];
    
    % Add each metric row
    for i = 1:length(metricsData)
        metric = metricsData{i};
        
        % Determine variability class based on CoV percentage
        covValue = str2double(metric{4});
        if covValue > 25
            variabilityClass = 'high-variability';
        else
            variabilityClass = 'low-variability';
        end
        
        htmlBody = [htmlBody, ...
            '<tr><td>' metric{1} '</td><td>' metric{2} '</td><td>' metric{3} ...
            '</td><td class="' variabilityClass '">' metric{4} '%</td><td>' metric{5} '</td></tr>'];
    end
    
    htmlBody = [htmlBody, '</table>'];
    
    % Interpretation notes
    htmlBody = [htmlBody, ...
        '<table>', ...
        '<tr><th>Correlation Interpretation</th></tr>', ...
        '<tr><td>', ...
        '• <span class="correlation-positive">Positive correlation</span>: Parameter increases → metric increases<br>', ...
        '• <span class="correlation-negative">Negative correlation</span>: Parameter increases → metric decreases<br>', ...
        '• Values close to ±1 indicate stronger relationships<br>', ...
        '• Values close to 0 indicate weak or no relationship<br><br>', ...
        '<strong>Variability (CoV):</strong> Lower percentages indicate more consistent performance<br>', ...
        '<strong>Color coding:</strong> <span class="low-variability">Green</span> = low variability, <span class="high-variability">Red</span> = high variability', ...
        '</td></tr>', ...
        '</table>'];
    
    % Complete HTML
    htmlContent = [htmlHeader, htmlBody, '</body></html>'];
end